// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  alternate_grid: dynamic(() => import("./ImageWithText")),
  boxes_list: dynamic(() => import("./BoxesList")),
  call_to_action: dynamic(() => import("./CallToAction")),
  chance_section: dynamic(() => import("./ChanceSection")),
  customer_logos: dynamic(() => import("./CustomerLogos")),
  diversity_section: dynamic(() => import("./DiversitySection")),
  company_carousel: dynamic(() => import("./CompanyCarousel")),
  faq_section: dynamic(() => import("./Faq")),
  feedback_section: dynamic(() => import("./FeedbackSection")),
  hero: dynamic(() => import("./Hero")),
  hero_section: dynamic(() => import("./HeroSection")),
  image: dynamic(() => import("./Image")),
  image_cards: dynamic(() => import("./ImageCards")),
  image_with_text_section: dynamic(() => import("./ImageWithTextSection")),
  process_section: dynamic(() => import("./ProcessSection")),
  question: dynamic(() => import("./Question")),
  quote: dynamic(() => import("./Quote")),
  section_box: dynamic(() => import("./SectionBox")),
  talent_section: dynamic(() => import("./TalentSection")),
  talents_numbers: dynamic(() => import("./TalentsNumbers")),
  text: dynamic(() => import("./Text")),
  text_with_image: dynamic(() => import("./TextWithImage")),
  text_with_image_inversed: dynamic(() => import("./TextWithImageInversed")),
  seo: dynamic(() => import("./SEO")),
};
